Hs/dev
rishabhghosh7/UnitTrackerV1 pull request #1
Opened 2024-05-22 17:27 UTC by hemantsharma1498

handlers for project and unit, relevant protos and migration script

2024-05-22 18:05 UTC, rishabhghosh7 requested changes
Looking good!

2024-05-22 18:05 UTC, rishabhghosh7 commented on proto/app.proto
> +
Wonder if it should be just `AddUnitRequest/Response` (vs `ToProject` suffix) because adding to project is 
1. the default behaviour (for now)
2. an implementation detail

2024-05-22 18:05 UTC, rishabhghosh7 commented on store/migrations/02_migration_hs.sql
> +DELETE * FROM Project WHERE name IN ("sports", "gym");
Migrations look good, by convention new migrations are only added on a release basis. So we could just continue using `01_init.sql`. Thoughts?

2024-05-22 18:05 UTC, rishabhghosh7 commented on store/migrations/03_migration_hs.sql
> +);
Missing auto increment int `ID`

2024-05-22 18:05 UTC, rishabhghosh7 commented on cmd/UnitTracker/main.go
> +}
This should have `CreateProjectRequest/Response`, same for `List`.

These 2 handlers are also missing logging found in `GetProject` handler

2024-05-22 18:05 UTC, rishabhghosh7 commented on cmd/UnitTracker/main.go
>  }
Same comment for request / response and logging

2024-05-22 18:05 UTC, rishabhghosh7 commented on cmd/UnitTracker/main.go
> +
We can remove this and the one for `Project` because GRPC gives us this for free (already available in the generated code)

2024-05-22 18:05 UTC, rishabhghosh7 commented on store/sqlite/sqlite.go
> +	name := strings.TrimSpace(project.Name)
If we have a constraint saying `No spaces allowed in names`, which approach are we taking?
1. User sets names with spaces and we accept it / store it. User founds out later that name `Day In The Park` is actually set as `DayInThePark`
2. User tries to set `Day In the Park` as name, but API gives error `spaces in names not allowed` and the request never reaches the db.

2024-05-22 18:05 UTC, rishabhghosh7 commented on store/sqlite/sqlite.go
> +
Solid function 💯

2024-05-22 18:05 UTC, rishabhghosh7 commented on store/sqlite/sqlite.go
> +
Nit : you don't need this, golang allows appending on nil slices (unlike other languages). 
Go however DOES NOT allow appending on nil MAPS.

2024-05-22 18:18 UTC, donnyeatstech commented on store/migrations/03_migration_hs.sql
> +);
we don't have to auto increment id here because a unit will be sent alongside a project_id

2024-05-22 18:20 UTC, donnyeatstech commented on store/sqlite/sqlite.go
> +	name := strings.TrimSpace(project.Name)
Trimspace will only remove spaces from the beginning and end of the string, `   Day in the park   ` becomes `Day in the park`

2024-05-22 18:47 UTC, rishabhghosh7 commented on proto/app.proto
> +  int32 project_id = 2;
Instead of `create_ts` we should have a general proto message `MetaTSInfo` (way better naming needed lol) which looks like
```
message XYZ {
  created ts = 1;
  updated ts = 2;
}

// use like
message Unit {
  ...fields 
  XYZ ts_info = 1;
}
```

Basically the whole idea is to have a general proto object that we can embed and reuse. Thoughts?

2024-05-24 14:22 UTC, hemantsharma1498 commented on proto/app.proto
> +  int32 project_id = 2;
if we're not going to be saving these fields in the db, where are we going to insert them? and how are we going to fetch them?

2024-05-26 00:00 UTC, merged